---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004-jenkins
  namespace: jenkins
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: pv0004-jenkins
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfsshare/pv0004/jenkins
    server: 192.168.1.195
