---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        namespace: jenkins
    spec:
      containers:
      - name: jenkins
        env:
        - name: JENKINS_OPTS
          valueFrom:
            secretKeyRef:
              name: jenkins-options
              key: jenkins-options
        image: jenkins/jenkins:lts
        ports:
          - name: https-port
            containerPort: 8083
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-pv-storage
            mountPath: /var/jenkins_home
          - name: jenkins-secret
            mountPath: /var/lib/jenkins/pki/
      volumes:
        - name: jenkins-pv-storage
          persistentVolumeClaim:
            claimName: pv0004-jenkins
        - name: jenkins-secret
          secret:
            secretName: jenkins
            items:
              - key: jenkins.jks
                path: jenkins.jks


