---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0004-jenkins
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pv0004-jenkins
  resources:
    requests:
      storage: 20Gi
